defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost


development:
  database: playpen_development
  <<: *defaults

test: &TEST
  database: playpen_test
  <<: *defaults

production:
  database: playpen_production
  <<: *defaults


cucumber:
  <<: *TEST
