#!/usr/bin/env ruby
begin
  require 'rubygems'
  require 'bundler'
#Bundler.require(:default, :test)
  require File.expand_path('../../.bundle/environment', __FILE__)
  load File.expand_path(File.dirname(__FILE__) + "/../gems/bin/cucumber")
end
